# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
name: Yusuf Fadairo
title: "Yusuf Fadairo's Portfolio"
email: hi@yusuffadairo.com
description: > # this means to ignore newlines until "baseurl:"
  The pesonal site of Yusuf Fadairo showcasing relevant history of development work as well as thought for the future 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.yusuffadairo.com" # the base hostname & protocol for your site
email: hi@yusuffadairo.com
phone: 16134025264
phone_safe: "1-613-402-five two six four"
twitter_username: InscrutableAfro
github_username:  yusuf-kami

# Build settings
markdown: kramdown
incremental: true
message:
  bye: "Come back, Please!"
  move: "You have the power after all!!"